### ISSUE TITLE
PostListing

### ISSUE THREAD

**Issue by polishedwp** [rmcfadzean/gatsby-pantry#10]
What is the reference in category.js:
`import PostListing from "../components/PostListing";`

Is there an additional package to be installed?

**Comment by JGallardo** [comment]
Came to ask the same thing. Looks like they did not add that example.

**Comment by rmcfadzean** [comment]
Hi,

Sorry this took me awhile to get to, it slipped my mind but your email reminded me, @JGallardo.

PostListing was just a basic component to spit out some posts.

I've added an example to the repo, I hope it helps. You can find it here: https://github.com/rmcfadzean/gatsby-pantry/blob/master/examples/starter-blog

I recommend copying out the bits you need instead using that as a base because it's very light on the features.

Let me know if you need any more help :)
